//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomInstallAction {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class CustomAction : global::System.Configuration.ApplicationSettingsBase {
        
        private static CustomAction defaultInstance = ((CustomAction)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CustomAction())));
        
        public static CustomAction Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GenericOD webservice")]
        public string ServerComment {
            get {
                return ((string)(this["ServerComment"]));
            }
            set {
                this["ServerComment"] = value;
            }
        }
    }
}
